### ISSUE TITLE
doesn't seem to compress HTML from html-webpack-plugin

### ISSUE THREAD

**Issue by graingert** [webpack-contrib/compression-webpack-plugin#30] opened 2016-05-05 10:37 UTC

**Comment by richtier** [comment] 2016-05-06 11:55
worth checking if changing `minThreshold` to a lower value will solve this, and ensure `test` includes html, e.g.,:

```js
    test: /\.js$|\.html$/,
    minRatio: 0,
```

**Comment by richtier** [comment] 2016-05-06 12:21
hmm actually I am getting this problem too now - intermittently.

**Comment by graingert** [comment] 2016-05-06 12:22
is this a plugin ordering issue? Is there a race between the HTML plugin and the compression plugin?

**Comment by ljfranklin** [comment] 2016-08-04 02:16
Ran into a similar problem here: https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/44. There's also a related discussion going on here: https://github.com/ampedandwired/html-webpack-plugin/issues/142.

**Comment by jantimon** [comment] 2016-10-20 07:15
This issue could be solved on the level of the compression-webpack-plugin - who is maintaining this plugin right now?

**Comment by TomDeBacker** [comment] 2016-12-07 17:07
bump

**Comment by TomDeBacker** [comment] 2016-12-07 23:51
@jantimon @graingert 
If it helps, I had the same issue and created a plugin that does this.
https://github.com/TomDeBacker/html-compression-webpack-plugin

**Comment by michael-ciniawsky** [comment] 2017-03-12 14:37
@jantimon  Can you explain how compression-webpack-plugin could solve the issue ?

**Comment by ijpiantanida** [comment] 2017-03-12 16:14
@michael-ciniawsky if I understand correctly, this would also be solved by #45. It's the same problem.

**Comment by jantimon** [comment] 2017-03-13 09:34
@michael-ciniawsky there is an event fired by the html-webpack-plugin which could be used

**Comment by michael-ciniawsky** [comment] 2017-03-13 15:45
@jantimon Mind to give 'this event' a name 😛 , in case #45 isn't resolving the problem?

**Comment by r3dDoX** [comment] 2017-04-07 10:51
I'm not exactly sure, but I have an issue that's maybe caused by the same root.

In my app I use CommonChunksPlugin to generate various bundle files including a manifest file like mentioned in the [docs](https://webpack.js.org/plugins/commons-chunk-plugin/#manifest-file).

For the bundle files the compression works just fine. But the manifest file isn't compressed. Might that be the same root cause?

**Comment by michael-ciniawsky** [comment] 2017-04-07 16:40
@r3dDoX Please provide more info on this + show some code 😛

**Comment by r3dDoX** [comment] 2017-04-14 14:16
@michael-ciniawsky  Sorry, didn't see the notification. Yeah so my webpack config basically looks like this:
`
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const CompressionPlugin = require("compression-webpack-plugin");

module.exports = {
  entry: './src/client/index.jsx',

  output: {
    path: path.join(__dirname, 'dist/'),
    filename: '[name].[chunkhash].js',
  },

  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
      {
        test: /\.svg$/,
        exclude: /node_modules/,
        loader: 'react-svg-inline-loader',
      },
    ],
  },

  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/client/index.html',
    }),
    new CopyWebpackPlugin([
      {
        from: 'src/client/assets/',
        to: 'assets/',
      }
    ]),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: function(module) {
        return module.context && module.context.indexOf("node_modules") !== -1;
      },
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      minChunks: Infinity
    }),
    new CompressionPlugin({
       asset: "[path].gz[query]",
       algorithm: "gzip",
       test: /\.js$/,
       threshold: 10240,
       minRatio: 0.8
     })
  ],
};
`

This results in a vendor.[hash].js.gz and a main.[hash].js.gz, but only a manifest.[hash].js and no manifest.js.gz.

**Comment by NeaSTDL** [comment] 2017-06-28 00:22
As just @r3dDoX comments, the same situation happened to me while I was setting up my bundling configuration. 


```
yarn build v0.24.6
$ webpack --config webpack-production.config.js --colors 
Hash: ce188de31b921a80fb52
Version: webpack 3.0.0

                         Assets             Size      Chunks                                  Chunk Names
manifest.json                           81 bytes                   [emitted]         
runtime.ce188de31b921a80fb52.js         8.41 kB       runtime      [emitted]                  runtime
vendor.66486fe933c2e8c9d06e.js          2.26 MB       vendor       [emitted]       [big]      vendor
main.79885a5e2710a6f17094.js.gz         1.03 MB                    [emitted]       [big]  
vendor.66486fe933c2e8c9d06e.js.gz       534 kB                     [emitted]       [big]  
main.79885a5e2710a6f17094.js            2.53 MB       main         [emitted]       [big]      main    
index.html                              1.93 kB                    [emitted] 
```

As can be seen in the extract of my bundle output, only main and vendor files got a gzipped version through compression-webpack-plugin.

Is there a way to tell compression-webpack-plugin to also create this file, or is it not relevant enough? 

In that case, I'll have to make some exceptions in my server application just for this file to be served without gzip encoding though.

**Comment by r3dDoX** [comment] 2017-06-30 11:12
@NeaSTDL That's exactly the workaround that I've been using since then...

**Comment by michael-ciniawsky** [comment] 2017-09-03 03:03
#71

**Closed** 2017-09-29 19:17 UTC
Labels: flag: Has pull request, priority: 4 (important), severity: 4 (inconvenient), type: Bug
