### ISSUE TITLE
Why I set deleteOriginalAssets : true, and get blank page?

### ISSUE THREAD

**Issue by kid1412621** [webpack-contrib/compression-webpack-plugin#120] opened 2019-05-07 08:48 UTC
set `deleteOriginalAssets: true`, and I checked it does delete origin asset files. However I get a blank page.
What does this config do exactly?
b.t.w I using vue cli3

**Comment by evilebottnawi** [comment] 2019-05-07 09:53
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

I don't know because you don't provide neither configuration nor reproducible test repo, i can't help without these stuff, sorry

**Closed by evilebottnawi** 2019-05-07 09:53 UTC

**Comment by kid1412621** [comment] 2019-05-07 13:17
> It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
> 
> I don't know because you don't provide neither configuration nor reproducible test repo, i can't help without these stuff, sorry

Sorry, didn't see the description of the last type.
