### ISSUE TITLE
Compressing files copied by 'copy-webpack-plugin'

### ISSUE THREAD

**Issue by CalebDelbridge** [webpack-contrib/compression-webpack-plugin#173] opened 2020-07-25 14:45 UTC
I'm still having this issue, i have tried downgrading using the forked repo and nothing has this been fixed yet?

Dependencies
```
    "compression-webpack-plugin": "^4.0.0",
    "copy-webpack-plugin": "^6.0.3",
```

webpack.config.js
```
const HtmlWebPackPlugin = require('html-webpack-plugin');
const autoprefixer = require('autoprefixer');
const path = require('path');
const CompressionPlugin = require('compression-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');
const ManifestPlugin = require('webpack-manifest-plugin');
const MinifyPlugin = require('babel-minify-webpack-plugin');

module.exports = {
  context: __dirname,
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'main.js',
    publicPath: '/',
  },
  devServer: {
    historyApiFallback: true,
  },
  resolve: {
    extensions: ['.js', '.jsx', '.less', '.css'],
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          plugins: [['import', { libraryName: 'antd', style: true }]],
        },
      },
      {
        test: /\.less$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          {
            loader: 'less-loader',
            options: {
              lessOptions: {
                javascriptEnabled: true,
              },
            },
          },
        ],
      },
      {
        test: /\.css$/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            options: {
              modules: {
                localIdentName: '[name]__[local]___[hash:base64:5]',
              },
              sourceMap: true,
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              ident: 'postcss',
              plugins: () => [autoprefixer({})],
            },
          },
        ],
      },
      {
        test: /\.(png|jpe?g|gif)$/,
        loader: 'url-loader?limit=10000&name=img/[name].[ext]',
      },
    ],
  },
  plugins: [
    new MinifyPlugin(),
    new ManifestPlugin({ fileName: 'file-manifest.json' }),
    new CopyPlugin([
      {
        from: 'public',
        to: 'dist',
        globOptions: {
          ignore: ['**/index.html'],
        },
      },
    ]),
    new CompressionPlugin({
      algorithm: 'gzip',
      cache: false,
      test: /\.(js|css|html|svg)$/,
      threshold: 10240,
      minRatio: 0.8,
      deleteOriginalAssets: false,
    }),
    new CompressionPlugin({
      filename: '[path].br[query]',
      algorithm: 'brotliCompress',
      test: /\.(js|css|html|svg)$/,
      compressionOptions: {
        level: 11,
      },
      cache: false,
      threshold: 10240,
      minRatio: 0.8,
      deleteOriginalAssets: false,
    }),
    new HtmlWebPackPlugin({
      template: path.resolve(__dirname, 'public/index.html'),
      filename: 'index.html',
    }),
  ],
};

```

_Originally posted by @CalebDelbridge in https://github.com/webpack-contrib/compression-webpack-plugin/issues/63#issuecomment-663863368_

**Comment by evilebottnawi** [comment] 2020-07-25 14:48
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please respect time other developers. Also I can't reproduce

**Comment by evilebottnawi** [comment] 2020-07-25 14:49
You should not never copy `dist` directory, because it is generated by `webpack`

**Closed by evilebottnawi** 2020-07-25 14:48 UTC

**Comment by CalebDelbridge** [comment] 2020-07-25 14:50
I'm not copying dist I'm copying a directory named `public` to go into `dist`

**Comment by CalebDelbridge** [comment] 2020-07-25 15:02
@evilebottnawi I have updated the original comment to follow the template

**Comment by evilebottnawi** [comment] 2020-07-25 15:08
`copy-webpack-plugin` is not created to copy generated assets from webpack, it is only to copy assets before build

**Comment by CalebDelbridge** [comment] 2020-07-25 15:18
So what do you suggest I use then?

**Comment by evilebottnawi** [comment] 2020-07-25 15:28
`compression-webpack-plugin` already compress all assets copied by `copy-webpack-plugin`, I can't see the problem

**Comment by CalebDelbridge** [comment] 2020-07-25 15:43
Strange I don't seem to be getting those results as you seem to be getting i'll keep tweaking and trying my config

**Comment by wiz-sheanqi** [comment] 2021-02-22 07:30
> Strange I don't seem to be getting those results as you seem to be getting i'll keep tweaking and trying my config, thank you

I didn't get the result either. Did you make it？

**Comment by kalitine** [comment] 2022-09-29 11:41
I have a few JS files to copy and compress, but the compression works for one file and I have no idea why. All files have the same file rights, all are in the same folder, just different content.
