### ISSUE TITLE
Compressing files copied by 'copy-webpack-plugin'

### ISSUE THREAD

**Issue by StasD** [webpack-contrib/compression-webpack-plugin#63] opened 2017-06-21 13:49 UTC
Hello,

This is my setup:
```
let CompressionPlugin = require('compression-webpack-plugin');
let CopyWebpackPlugin = require('copy-webpack-plugin');
...
        new CopyWebpackPlugin([{ from: 'src/assets', to: 'assets' }]),

        new CompressionPlugin({
            asset: '[path].gz',
            algorithm: 'gzip',
            test:  /\.(js|css|map|po)$/,
            // threshold: 10240,
            minRatio: 10  // 0.8
        }),
```
The problem is that .po files, which are in src/assets/translations, and which are copied by the CopyWebpackPlugin don't get compressed by the CompressionPlugin.
Not sure who's plugin fault it is. :)
Is it possible to get it work as intended?

Thanks!

**Comment by nmcclay** [comment] 2017-07-29 20:55
I am also interested in a solution to this problem, not certain where the issue stems from...

**Comment by nmcclay** [comment] 2017-07-29 21:44
I can confirm that [this PR](https://github.com/webpack-contrib/compression-webpack-plugin/pull/45#pullrequestreview-28255166) fixed by issues with the following config:
```
plugins: [
    new CopyWebpackPlugin([{
      from: path.resolve(__dirname, '../my-other-project/dist'),
      to: 'static'
    }]),
    new CompressionPlugin({
      // asset: "[path].gz[query]",
      algorithm: "gzip",
      test: /\.(js|html|css)$/
    })
  ]
```

**Comment by evilebottnawi** [comment] 2017-07-31 09:12
@nmcclay why don't use https://github.com/perchlayer/po-loader or https://github.com/queicherius/i18next-po-loader for this purpose?

**Comment by nmcclay** [comment] 2017-07-31 12:39
The problem was the order of execution for generating gzip compression after copying an external SPA app directory in my case, not moving .po files.  The issue just manifests as the same issue, that the CompressorPlugin wasn't running AFTER the copy plugin.  Using this fork effectively fixed that load issue in my case.

**Comment by keemor** [comment] 2017-08-28 13:18
@nmcclay Can you say what actually solved you problem?

My config:

```
new CopyWebpackPlugin([
    {
        from: path.join(__dirname, 'dev/json/info.json'),
        to: 'json/info.json'
    }
]),
new CompressionPlugin({
    asset: '[path].gz[query]',
    algorithm: 'gzip',
    test: /\.js$|\.json$|\.css$|\.html$/,
    deleteOriginalAssets: true
})
```
info.json is **not** gzipped in this case

**Comment by nmcclay** [comment] 2017-08-28 14:09
Its either that your path configuration is too rigid for CopyWebpackPlugin, or your CompressionPlugin test is incorrect, not sure which.  This configuration works with .json files for me:
```
plugins: [
    new CopyWebpackPlugin([{
      from: path.resolve(__dirname, '../my-other-project/dist'),
      to: 'static'
    }]),
    new CompressionPlugin({
      asset: "[path].gz[query]",
      algorithm: "gzip",
      test: /\.(js|css|json)$/
    })
  ]
```

**Comment by nmcclay** [comment] 2017-08-28 14:10
dependencies, note that I'm using aforementioned forked version of compression-webpack-plugin:
```
"webpack": "^3.4.1",
"compression-webpack-plugin": "github:ijpiantanida/compression-webpack-plugin#emit-event",
"copy-webpack-plugin": "^4.0.1",
```

**Comment by keemor** [comment] 2017-08-29 08:48
This helped and json is gzipped:
 
`"compression-webpack-plugin": "github:ijpiantanida/compression-webpack-plugin#emit-event",`

but know flag _deleteOriginalAssets_  doesn't work.

Thanks for the tip

**Closed** 2017-09-29 19:17 UTC
Labels: flag: Has pull request, priority: 4 (important), severity: 4 (inconvenient), type: Bug

**Comment by ashwinirajput** [comment] 2018-02-22 12:29
I have also same problem it working fine in chrome Chrome/63.0.3239.132 Safari/537.36

**Comment by CalebDelbridge** [comment] 2020-07-25 14:45
I'm still having this issue, i have tried downgrading using the forked repo and nothing has this been fixed yet?

Dependencies
```
    "compression-webpack-plugin": "^4.0.0",
    "copy-webpack-plugin": "^6.0.3",
```

webpack.config.js
```
const HtmlWebPackPlugin = require('html-webpack-plugin');
const autoprefixer = require('autoprefixer');
const path = require('path');
const CompressionPlugin = require('compression-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');
const ManifestPlugin = require('webpack-manifest-plugin');
const MinifyPlugin = require('babel-minify-webpack-plugin');

module.exports = {
  context: __dirname,
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'main.js',
    publicPath: '/',
  },
  devServer: {
    historyApiFallback: true,
  },
  resolve: {
    extensions: ['.js', '.jsx', '.less', '.css'],
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          plugins: [['import', { libraryName: 'antd', style: true }]],
        },
      },
      {
        test: /\.less$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          {
            loader: 'less-loader',
            options: {
              lessOptions: {
                javascriptEnabled: true,
              },
            },
          },
        ],
      },
      {
        test: /\.css$/,
        use: [
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            options: {
              modules: {
                localIdentName: '[name]__[local]___[hash:base64:5]',
              },
              sourceMap: true,
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              ident: 'postcss',
              plugins: () => [autoprefixer({})],
            },
          },
        ],
      },
      {
        test: /\.(png|jpe?g|gif)$/,
        loader: 'url-loader?limit=10000&name=img/[name].[ext]',
      },
    ],
  },
  plugins: [
    new MinifyPlugin(),
    new ManifestPlugin({ fileName: 'file-manifest.json' }),
    new CopyPlugin([
      {
        from: 'public',
        to: 'dist',
        globOptions: {
          ignore: ['**/index.html'],
        },
      },
    ]),
    new CompressionPlugin({
      algorithm: 'gzip',
      cache: false,
      test: /\.(js|css|html|svg)$/,
      threshold: 10240,
      minRatio: 0.8,
      deleteOriginalAssets: false,
    }),
    new CompressionPlugin({
      filename: '[path].br[query]',
      algorithm: 'brotliCompress',
      test: /\.(js|css|html|svg)$/,
      compressionOptions: {
        level: 11,
      },
      cache: false,
      threshold: 10240,
      minRatio: 0.8,
      deleteOriginalAssets: false,
    }),
    new HtmlWebPackPlugin({
      template: path.resolve(__dirname, 'public/index.html'),
      filename: 'index.html',
    }),
  ],
};

```
