### ISSUE TITLE
TypeError: Invalid non-string/buffer chunk in v0.3 (worked in v0.2).

### ISSUE THREAD

**Issue by samkelleher** [webpack-contrib/compression-webpack-plugin#16] opened 2016-01-25 00:20 UTC
In the webpack config under `plugins`.

```
new CompressionPlugin({    
   test: /\.js$/
})
```

The `regExp` was renamed as per the breaking change. But nothing else has changed. The build will succeed in v0.2 but gets the error in v0.3

Stacktrace:

```
TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:178:14)
    at Gzip.Writable.write (_stream_writable.js:205:12)
    at Gzip.Writable.end (_stream_writable.js:433:10)
    at zlibBuffer (zlib.js:197:10)
    at Object.exports.gzip (zlib.js:123:10)
    at CompressionPlugin.<anonymous> (<Project>/node_modules/compression-webpack-plugin/index.js:68:10)
    at <Project>/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (<Project>/node_modules/async/lib/async.js:32:24)
    at Object.async.each (<Project>/node_modules/async/lib/async.js:110:9)
    at CompressionPlugin.<anonymous> (<Project>/node_modules/compression-webpack-plugin/index.js:55:10)
    at Compilation.applyPluginsAsync (<Project>/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (<Project>/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (<Project>/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (<Project>/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:137:4)
    at Compilation.applyPluginsAsync (<Project>/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (<Project>/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (<Project>/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (<Project>/node_modules/extract-text-webpack-plugin/index.js:309:4)
    at Compilation.applyPluginsAsync (<Project>/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (<Project>/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (<Project>/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (<Project>/node_modules/extract-text-webpack-plugin/index.js:285:5)
    at <Project>/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (<Project>/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (<Project>/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:209:22)
    at ExtractTextPlugin.<anonymous> (<Project>/node_modules/extract-text-webpack-plugin/index.js:237:10)
    at Compilation.applyPluginsAsync (<Project>/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.seal (<Project>/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (<Project>/node_modules/webpack/lib/Compiler.js:397:15)
```

**Comment by samkelleher** [comment] 2016-01-25 00:37
Can confirm that rolling back to 0.2 works normally with no other changes.

**Comment by calvinl** [comment] 2016-01-25 19:17
Just saw this error as well. Confirmed rolling back to `0.2.0` works.

**Comment by mjrussell** [comment] 2016-01-25 19:51
:+1:

**Comment by AymanNatsheh** [comment] 2016-01-26 10:38
rolling back to 0.2.0 works

**Comment by canvaskisa** [comment] 2016-01-27 17:12
Also facing this issue.

**Comment by hqxluoyang** [comment] 2016-02-02 02:43
And I just happened to meet.

**Comment by Icehunter** [comment] 2016-02-04 22:28
I have this same issue as well.  My bigger concern is why this repo is not following semver?  I saw 0.3.0 was published as a "breaking change".  Should that not have been 1.0.0?  Because NPM uses ^X.X.X by default this just possibly will break anyone's usage unless they explicitly hardcode versions.

**Comment by Icehunter** [comment] 2016-02-05 01:15
Fix proposed:
https://github.com/webpack/compression-webpack-plugin/pull/17

**Comment by jsg2021** [comment] 2016-02-05 16:43
@Icehunter it is kindof semvar :)

http://semver.npmjs.com/ put in "^0.2.0" for "compression-webpack-plugin" and see that only 0.2.0 is highlighted.

**Comment by Icehunter** [comment] 2016-02-05 17:40
@jsg2021 They may not have updated the front portion of the site but the default behavior of NPM has changed since 4+.

Such as if you do:
npm i hapi@^11.0.0
test@0.0.0 /Users/icehunter/GitHub/nodeplayground
└── hapi@11.1.4  extraneous

The same if I did:
npm i hapi@^10.0.0
test@0.0.0 /Users/icehunter/GitHub/nodeplayground
└── hapi@10.5.0  extraneous

If you click through to https://docs.npmjs.com/getting-started/semantic-versioning you can see that they have it as:

Patch releases: 1.0 or 1.0.x or ~1.0.4
Minor releases: 1 or 1.x or ^1.0.4
Major releases: * or x

So ^1.0.4 and 1.x are the same.

**Comment by cchamberlain** [comment] 2016-02-06 02:32
This has been breaking my builds and throwing lots of errors since the inclusion of the node-zopfli stuff on windows.

**Comment by cchamberlain** [comment] 2016-02-06 02:55
Also @Icehunter, anything semver 0.x.x is considered initial development and may change at any time.  See http://semver.org/#spec-item-4

**Comment by Icehunter** [comment] 2016-02-06 03:31
Fair enough. I'll wait till this hits 1.0 to use it then. Personally though even if it's under 0.X I follow it as much as I can :)

**Comment by jsg2021** [comment] 2016-02-06 18:13
@Icehunter "^0.x.y" is special case... just as @cchamberlain said. when the major is "0" the caret makes minor locked.

**Comment by cchamberlain** [comment] 2016-02-09 04:54
@Icehunter I've been using 0.2.0 in prod for some time on Windows and OSX and haven't had any issues until 0.3.0. :beers:

**Comment by graingert** [comment] 2016-02-16 09:21
yeah I get this problem also

**Comment by robbyoconnor** [comment] 2016-02-18 00:55
I got this issue too

**Comment by zjhiphop** [comment] 2016-02-25 00:57
Any progress for this issue?

**Comment by zjhiphop** [comment] 2016-02-25 01:01
The 0.2.0 works, but the build result seems strange. 
The config i used: 
```{
        asset: "[path].gz[query]",
        algorithm: "gzip",
        test: /\.js$|\.html$/,
        threshold: 10240,
        minRatio: 0.8
    }
```
After build, there generated a file named with '[path].gz[query]', that's so boring. Any one could help with it?

**Comment by calvinl** [comment] 2016-02-25 03:47
@zjhiphop that the syntax for `0.3.0`. Try it with `{file}.gz` instead if you're using `0.2.0`.

**Comment by dshorowitz** [comment] 2016-03-25 13:56
+1 Also have this issue

**Comment by mathieumg** [comment] 2016-03-29 20:33
Fixed in v0.3.1, this could be closed!

**Comment by jornare** [comment] 2016-03-30 11:29
All the change I can see in 1.3.1 is the bump in version. Am I mistaken?

**Comment by graingert** [comment] 2016-03-30 11:31
@jornare https://github.com/webpack/compression-webpack-plugin/compare/v0.3.0...v0.3.1

**Closed** 2017-03-12 14:51 UTC
